
services:

  vault-dev:
    image: hashicorp/vault:latest
    container_name: vault-dev
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroottoken
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - "8200:8200"

  db-dev:
    image: postgres:17
    container_name: db-dev
    environment:
      POSTGRES_DB: sysadminanywhere
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    ports:
      - "5432:5432"

  n8n:
    image: n8nio/n8n:stable
    container_name: n8n-dev
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_ENDPOINT_WEBHOOK=true
      - N8N_PROTOCOL=http