databaseChangeLog:
  - changeSet:
      id: settings
      author: Igor Markin
      preConditions:
        - onFail: MARK_RAN
          not:
            tableExists:
              tableName: settings
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: settings_pkey
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: loginid
                  type: BIGINT
              - column:
                  constraints:
                    nullable: true
                  name: json
                  type: TEXT
            tableName: settings

        - addForeignKeyConstraint:
            baseTableName: settings
            baseColumnNames: loginid
            referencedTableName: logins
            referencedColumnNames: id
            constraintName: fk_settings_logins
