spring.application.name=incident

server.port=${PORT:8083}

# PostgreSQL configuration.
spring.datasource.url = jdbc:postgresql://${DB_ADDRESS:localhost}:${DB_PORT:5432}/${DB_BASE:incident}
spring.datasource.username = ${DB_USER:postgres}
spring.datasource.password = ${DB_PASSWORD:password}
spring.jpa.hibernate.ddl-auto = update

spring.liquibase.enabled = false

cron.expression=${SCAN.CRON:0 0 0 * * *}

#LDAP ReadOnly User
wef.server = ${WEF_SERVER:localhost}
wef.port = ${WEF_PORT:5985}
wef.username = ${WEF_USERNAME:}
wef.password = ${WEF_PASSWORD:}
wef.use.ssl = ${WEF_USE_SSL:false}

app.services.directory.uri = ${DIRECTORY_SERVICE:http://localhost:8081}

app.jwt.secret = ${JWT_SECRET:secret}

# Disable default generated 'user' credentials from Spring Boot auto-configuration.
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

